name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v5
    - name: patch misc/conftest.cpp
      run: git apply 0001-conftest.cpp.patch
    - name: cmake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: build
      run: cmake --build build --config ${{ matrix.build_type }}
    - name: test
      run: ctest --output-on-failure --test-dir build -C ${{ matrix.build_type }}
